import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, Show, SignInButton, SignUpButton } from '@clerk/nextjs'
import Navbar from "../component/Navbar"
import Footer from "../component/Footer"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
          {/* only show when the user is sign-out */}
          {/* <Show when="signed-out">
         <div>
              <SignInButton mode="modal">
                <button className="border border-gray-300 px-6 py-2 rounded-lg font-medium hover:bg-gray-50">
                  Login
                </button>
              </SignInButton>

              <SignUpButton mode="modal">
                <button className="bg-[#6c47ff] text-white px-6 py-2 rounded-lg font-medium hover:bg-opacity-90">
                  Get Started for Free
                </button>
              </SignUpButton>
            </div>
          </Show> */}

          {/* only show the main home page or other pages when the user is sign in  */}
          {/* <Show when="signed-in"> */}
          <Navbar/>
            {children}
          {/* </Show> */}
 <Footer/>
      </body>
    </html>
           </ClerkProvider>
  );
}